// <auto-generated />
using System;
using AgroControl.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroControl.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611161743_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroControl.API.Models.Afastamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataAfastamento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_afastamento");

                    b.Property<DateTime?>("DataRetorno")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_retorno");

                    b.Property<string>("MotivoAfastamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("motivo_afastamento");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacao");

                    b.Property<int?>("PeriodoCarencia")
                        .HasColumnType("int")
                        .HasColumnName("periodo_carencia");

                    b.Property<string>("ProdutoUtilizado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("produto_utilizado");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("AFASTAMENTO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_alerta");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Lido")
                        .HasColumnType("bit")
                        .HasColumnName("lido");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("ALERTA", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ativo");

                    b.Property<string>("Brinco")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("brinco");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_entrada");

                    b.Property<string>("DataEntradaInformada")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("data_entrada_informada");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("DataNascimentoInformada")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("data_nascimento_informada");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_saida");

                    b.Property<string>("DataSaidaInformada")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("data_saida_informada");

                    b.Property<int?>("MaeAnimalId")
                        .HasColumnType("int")
                        .HasColumnName("mae_animal_id");

                    b.Property<string>("MarcaSinal")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("marca_sinal");

                    b.Property<string>("MotivoSaida")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("motivo_saida");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeMae")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_mae");

                    b.Property<string>("NomePai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_pai");

                    b.Property<string>("NumeroAnimal")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("numero_animal");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<int?>("PaiAnimalId")
                        .HasColumnType("int")
                        .HasColumnName("pai_animal_id");

                    b.Property<string>("Procedencia")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("procedencia");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("raca");

                    b.Property<string>("Raca2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("raca2");

                    b.Property<string>("RacaMae")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("raca_mae");

                    b.Property<string>("RacaPai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("raca_pai");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("sexo");

                    b.Property<string>("StatusLeite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status_leite");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("MaeAnimalId");

                    b.HasIndex("PaiAnimalId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("ANIMAL", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_evento");

                    b.Property<decimal?>("LeiteLitrosDia")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("leite_litros_dia");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso_kg");

                    b.Property<decimal?>("RacaoKgDia")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("racao_kg_dia");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ANIMAL_EVENTO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FotoBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("foto_base64");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "Ordem")
                        .IsUnique();

                    b.ToTable("ANIMAL_FOTO", null, t =>
                        {
                            t.HasCheckConstraint("CK_ANIMAL_FOTO_ORDEM", "ordem BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalLactacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataParto")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_parto");

                    b.Property<DateTime?>("DataSecagem")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_secagem");

                    b.Property<int?>("DiasLactacao")
                        .HasColumnType("int")
                        .HasColumnName("dias_lactacao");

                    b.Property<DateTime?>("InicioControle")
                        .HasColumnType("datetime2")
                        .HasColumnName("inicio_controle");

                    b.Property<decimal?>("MediaDiaria")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("media_diaria");

                    b.Property<int>("NumeroLactacao")
                        .HasColumnType("int")
                        .HasColumnName("numero_lactacao");

                    b.Property<decimal?>("ProducaoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("producao_total");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ANIMAL_LACTACAO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalReproducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_evento");

                    b.Property<string>("Inseminador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("inseminador");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<DateTime?>("PrevisaoParto")
                        .HasColumnType("datetime2")
                        .HasColumnName("previsao_parto");

                    b.Property<string>("Reprodutor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reprodutor");

                    b.Property<string>("Resultado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resultado");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ANIMAL_REPRODUCAO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalSaudeRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_registro");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dose");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<string>("ProdutoUtilizado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("produto_utilizado");

                    b.Property<DateTime?>("ProximaAplicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("proxima_aplicacao");

                    b.Property<string>("TipoRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_registro");

                    b.Property<string>("Veterinario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("veterinario");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ANIMAL_SAUDE_REGISTRO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalVacina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_aplicacao");

                    b.Property<string>("Dose")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("dose");

                    b.Property<string>("NomeVacina")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_vacina");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<DateTime?>("ProximaAplicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("proxima_aplicacao");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ANIMAL_VACINA", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_despesa");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("DESPESA", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.EstoqueMedicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantidade_atual");

                    b.Property<decimal?>("QuantidadeMinima")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantidade_minima");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unidade");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("ESTOQUE_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.EstoqueMovimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimalId")
                        .HasColumnType("int")
                        .HasColumnName("animal_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_movimentacao");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("int")
                        .HasColumnName("estoque_id");

                    b.Property<string>("Motivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantidade");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_movimentacao");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("EstoqueId");

                    b.ToTable("ESTOQUE_MOVIMENTACAO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("estado");

                    b.Property<string>("FocoProdutivo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ambos")
                        .HasColumnName("foco_produtivo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("PROPRIEDADE", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.PropriedadeArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AreaHectares")
                        .HasColumnType("decimal(12,4)")
                        .HasColumnName("area_hectares");

                    b.Property<int?>("AreaPaiId")
                        .HasColumnType("int")
                        .HasColumnName("area_pai_id");

                    b.Property<string>("CoordenadasGeojson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("coordenadas_geojson");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("cor");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("TipoArea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_area");

                    b.Property<string>("TipoCadastro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("AREA_INTERNA")
                        .HasColumnName("tipo_cadastro");

                    b.HasKey("Id");

                    b.HasIndex("AreaPaiId");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("PROPRIEDADE_AREA", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.PropriedadePonto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("observacao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("PROPRIEDADE_PONTO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DataReceita")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_receita");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Outros")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("RECEITA", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usuario");

                    b.Property<int>("PropriedadeId")
                        .HasColumnType("int")
                        .HasColumnName("propriedade_id");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("PropriedadeId");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("AgroControl.API.Models.Afastamento", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.Alerta", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.Animal", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "MaeAnimal")
                        .WithMany()
                        .HasForeignKey("MaeAnimalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AgroControl.API.Models.Animal", "PaiAnimal")
                        .WithMany()
                        .HasForeignKey("PaiAnimalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaeAnimal");

                    b.Navigation("PaiAnimal");

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalEvento", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany("Eventos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalFoto", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany("Fotos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalLactacao", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany("Lactacoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalReproducao", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany("Reproducoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalSaudeRegistro", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany("SaudeRegistros")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroControl.API.Models.AnimalVacina", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany("Vacinas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("AgroControl.API.Models.Despesa", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.EstoqueMedicamento", b =>
                {
                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.EstoqueMovimentacao", b =>
                {
                    b.HasOne("AgroControl.API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId");

                    b.HasOne("AgroControl.API.Models.EstoqueMedicamento", "Estoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Estoque");
                });

            modelBuilder.Entity("AgroControl.API.Models.PropriedadeArea", b =>
                {
                    b.HasOne("AgroControl.API.Models.PropriedadeArea", "AreaPai")
                        .WithMany("AreasInternas")
                        .HasForeignKey("AreaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany("Areas")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaPai");

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.PropriedadePonto", b =>
                {
                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany("Pontos")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.Receita", b =>
                {
                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany()
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.Usuario", b =>
                {
                    b.HasOne("AgroControl.API.Models.Propriedade", "Propriedade")
                        .WithMany("Usuarios")
                        .HasForeignKey("PropriedadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propriedade");
                });

            modelBuilder.Entity("AgroControl.API.Models.Animal", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Fotos");

                    b.Navigation("Lactacoes");

                    b.Navigation("Reproducoes");

                    b.Navigation("SaudeRegistros");

                    b.Navigation("Vacinas");
                });

            modelBuilder.Entity("AgroControl.API.Models.EstoqueMedicamento", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("AgroControl.API.Models.Propriedade", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Pontos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AgroControl.API.Models.PropriedadeArea", b =>
                {
                    b.Navigation("AreasInternas");
                });
#pragma warning restore 612, 618
        }
    }
}
